jobs:
  - job: Build
    displayName: 'Build'

    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: NodeTool@0
        displayName: 'Install Node'
        inputs:
          versionSpec: '12.x'

      - task: Cache@2
        displayName: 'Check Cache'
        inputs:
          key: 'yarn | yarn.lock'
          path: 'node_modules'
          cacheHitVar: CACHE_RESTORED

      - script: 'yarn install --frozen-lockfile'
        displayName: 'Install Dependencies'
        condition: ne(variables.CACHE_RESTORED, 'true')

      - script: 'yarn build'
        displayName: 'Build'
