jobs:
  - job: Test
    displayName: "Test"

    pool:
      vmImage: "ubuntu-latest"

    steps:
      - task: NodeTool@0
        displayName: "Install Node"
        inputs:
          versionSpec: "12.x"

      - task: Cache@2
        displayName: "Check Cache"
        inputs:
          key: "yarn | yarn.lock"
          path: "node_modules"
          cacheHitVar: CACHE_RESTORED

      - script: "yarn install --frozen-lockfile"
        displayName: "Install Dependencies"
        condition: ne(variables.CACHE_RESTORED, 'true')

      - script: "yarn run test"
        displayName: "Run Jest"

      - task: PublishCodeCoverageResults@1
        displayName: "Publish Coverage Results"
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml
