trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'
pr:
  branches:
    include:
      - '*'
jobs:
  - template: azure-pipelines-lint.yml
  - template: azure-pipelines-build.yml
