jobs:
  - job: Build
    displayName: 'Build'

    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: NodeTool@0
        displayName: 'Install Node'
        inputs:
          versionSpec: '12.x'

      - task: Cache@2
        displayName: 'Check Cache'
        inputs:
          key: 'yarn | yarn.lock'
          path: 'node_modules'
          cacheHitVar: CACHE_RESTORED

      - script: 'yarn install --frozen-lockfile'
        displayName: 'Install Dependencies'
        condition: ne(variables.CACHE_RESTORED, 'true')

      - script: 'yarn build'
        displayName: 'Build'

  - job: BuildDocker
    displayName: 'Build Docker Images'

    pool:
      vmImage: 'ubuntu-latest'

    variables:
      - DOCKER_CLI_EXPERIMENTAL: enabled
      - name: Version
        value: $[replace(variables['Build.SourceBranch'],'refs/tags/v','')]

    steps:
      - task: CmdLine@2
        displayName: 'Register Qemu Binfmt and Docker Buildx Builder'
        inputs:
          script: |
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker buildx create --name builder
            docker buildx use builder

      - task: CmdLine@2
        displayName: 'Build and Push Unstable Docker Image'
        condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/master')
        inputs:
          script: |
            docker buildx build --no-cache --push \
              --platform linux/arm,linux/arm64,linux/amd64 \
              --tag jellyfin/jellyfin-vue:unstable-$(Build.BuildNumber) \
              --tag jellyfin/jellyfin-vue:unstable

      - task: CmdLine@2
        displayName: 'Build and Push Stable Docker Image'
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
        inputs:
          script: |
            docker buildx build --no-cache --push \
              --platform linux/arm,linux/arm64,linux/amd64 \
              --tag jellyfin/jellyfin-vue:$(Version) \
              --tag jellyfin/jellyfin-vue:stable \
              --tag jellyfin/jellyfin-vue:latest
