name: "Label pull requests"
on:
  - pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@main
        continue-on-error: true
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
